## 2D LED Matrix

In [1]:
import numpy as np

from ledmap import make_array
from ledmap.matrix import make_matrix, serpentine
from ledmap.util import get_string
from ledmap.wled import dump as dump_wled
from ledmap.wled import to_dict as to_wled

## Simple matrix

In [2]:
m = make_matrix(3, 4)

In [3]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
to_wled(m)

{'map': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'width': 4, 'height': 3}

In [5]:
# for WLED
print(get_string(lambda f: dump_wled(m, f)))

{"map":[0,1,2,3,4,5,6,7,8,9,10,11],"width":4,"height":3}


## Transposed matrix

In [6]:
m = make_matrix(3, 4, vertical=True)

In [7]:
# Alternative
np.array_equal(m, make_matrix(4, 3).T)

True

In [8]:
m

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [9]:
to_wled(m)

{'map': [0, 3, 6, 9, 1, 4, 7, 10, 2, 5, 8, 11], 'width': 4, 'height': 3}

## Serpentine matrix

In [10]:
make_matrix(3, 4, serpentine=True)

array([[ 0,  1,  2,  3],
       [ 7,  6,  5,  4],
       [ 8,  9, 10, 11]])

In [11]:
make_matrix(3, 4, serpentine=True, vertical=True)

array([[ 0,  5,  6, 11],
       [ 1,  4,  7, 10],
       [ 2,  3,  8,  9]])

## Complex matrix

In [12]:
m = np.rot90(serpentine(make_matrix(3, 4)))
m = np.where((m >= 1) & (m <= 10), m, -1)

In [13]:
m

array([[ 3,  4, -1],
       [ 2,  5, 10],
       [ 1,  6,  9],
       [-1,  7,  8]])

## Arbitrary matrix

In [14]:
m = make_array(
    [14, 13, 12, 10, 9, 8, 7, 6, -1, 5, 4, 3, -1, -1, 2, 1, -1, -1, -1, 0], width=4
)

In [15]:
m

array([[14, 13, 12, 10],
       [ 9,  8,  7,  6],
       [-1,  5,  4,  3],
       [-1, -1,  2,  1],
       [-1, -1, -1,  0]])

In [16]:
to_wled(m)

{'map': [14, 13, 12, 10, 9, 8, 7, 6, -1, 5, 4, 3, -1, -1, 2, 1, -1, -1, -1, 0],
 'width': 4,
 'height': 5}